webtalk_init -webtalk_dir /net/s/lmartin042/project_1/project_1.sim/sim_2/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 11 15:08:33 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "202409907_1777491908_210660663_640" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e94d51247a09516b8ec14c94ef04df36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d918786533734a2f8580551ad7192f53" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.8.2003 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1240 v5 @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3789.886 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132304_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2879167346 -regid "202409907_1777491908_210660663_640" -xml /net/s/lmartin042/project_1/project_1.sim/sim_2/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /net/s/lmartin042/project_1/project_1.sim/sim_2/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /net/s/lmartin042/project_1/project_1.sim/sim_2/behav/xsim/xsim.dir/PGCD_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
